version: '3.8'
services:
  web:
    build: .
    environment:
      - STAGE=production # TODO: Remove stage.
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/gymbuddy
    ports:
      - "8001:8000"
    volumes:
      - "${HOME}/.m2:/root/.m2"
    depends_on:
      - db
  db:
    image: postgres:14.6-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gymbuddy
    ports:
      - '5432'
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
volumes:
  db:
    driver: local
