/*
 * This file is generated by jOOQ.
 */
package dev.anthonybruno.gymbuddy.db.jooq.tables.records


import dev.anthonybruno.gymbuddy.db.jooq.tables.Users

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record4
import org.jooq.Row4
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
class UsersRecord() : UpdatableRecordImpl<UsersRecord>(Users.USERS), Record4<Int?, String?, String?, String?> {

    var id: Int?
        set(value) = set(0, value)
        get() = get(0) as Int?

    var email: String?
        set(value) = set(1, value)
        get() = get(1) as String?

    var password: String?
        set(value) = set(2, value)
        get() = get(2) as String?

    var timezone: String?
        set(value) = set(3, value)
        get() = get(3) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row4<Int?, String?, String?, String?> = super.fieldsRow() as Row4<Int?, String?, String?, String?>
    override fun valuesRow(): Row4<Int?, String?, String?, String?> = super.valuesRow() as Row4<Int?, String?, String?, String?>
    override fun field1(): Field<Int?> = Users.USERS.ID
    override fun field2(): Field<String?> = Users.USERS.EMAIL
    override fun field3(): Field<String?> = Users.USERS.PASSWORD
    override fun field4(): Field<String?> = Users.USERS.TIMEZONE
    override fun component1(): Int? = id
    override fun component2(): String? = email
    override fun component3(): String? = password
    override fun component4(): String? = timezone
    override fun value1(): Int? = id
    override fun value2(): String? = email
    override fun value3(): String? = password
    override fun value4(): String? = timezone

    override fun value1(value: Int?): UsersRecord {
        id = value
        return this
    }

    override fun value2(value: String?): UsersRecord {
        email = value
        return this
    }

    override fun value3(value: String?): UsersRecord {
        password = value
        return this
    }

    override fun value4(value: String?): UsersRecord {
        timezone = value
        return this
    }

    override fun values(value1: Int?, value2: String?, value3: String?, value4: String?): UsersRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        return this
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    constructor(id: Int? = null, email: String? = null, password: String? = null, timezone: String? = null): this() {
        this.id = id
        this.email = email
        this.password = password
        this.timezone = timezone
    }
}
