/*
 * This file is generated by jOOQ.
 */
package dev.anthonybruno.gymbuddy.db.jooq.tables.records


import dev.anthonybruno.gymbuddy.db.jooq.tables.Workouts

import java.time.OffsetDateTime

import org.jooq.Field
import org.jooq.Record1
import org.jooq.Record6
import org.jooq.Row6
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
class WorkoutsRecord() : UpdatableRecordImpl<WorkoutsRecord>(Workouts.WORKOUTS), Record6<Int?, Int?, String?, String?, OffsetDateTime?, String?> {

    var id: Int?
        set(value) = set(0, value)
        get() = get(0) as Int?

    var userId: Int?
        set(value) = set(1, value)
        get() = get(1) as Int?

    var title: String?
        set(value) = set(2, value)
        get() = get(2) as String?

    var description: String?
        set(value) = set(3, value)
        get() = get(3) as String?

    var date: OffsetDateTime?
        set(value) = set(4, value)
        get() = get(4) as OffsetDateTime?

    var timezone: String?
        set(value) = set(5, value)
        get() = get(5) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    override fun fieldsRow(): Row6<Int?, Int?, String?, String?, OffsetDateTime?, String?> = super.fieldsRow() as Row6<Int?, Int?, String?, String?, OffsetDateTime?, String?>
    override fun valuesRow(): Row6<Int?, Int?, String?, String?, OffsetDateTime?, String?> = super.valuesRow() as Row6<Int?, Int?, String?, String?, OffsetDateTime?, String?>
    override fun field1(): Field<Int?> = Workouts.WORKOUTS.ID
    override fun field2(): Field<Int?> = Workouts.WORKOUTS.USER_ID
    override fun field3(): Field<String?> = Workouts.WORKOUTS.TITLE
    override fun field4(): Field<String?> = Workouts.WORKOUTS.DESCRIPTION
    override fun field5(): Field<OffsetDateTime?> = Workouts.WORKOUTS.DATE
    override fun field6(): Field<String?> = Workouts.WORKOUTS.TIMEZONE
    override fun component1(): Int? = id
    override fun component2(): Int? = userId
    override fun component3(): String? = title
    override fun component4(): String? = description
    override fun component5(): OffsetDateTime? = date
    override fun component6(): String? = timezone
    override fun value1(): Int? = id
    override fun value2(): Int? = userId
    override fun value3(): String? = title
    override fun value4(): String? = description
    override fun value5(): OffsetDateTime? = date
    override fun value6(): String? = timezone

    override fun value1(value: Int?): WorkoutsRecord {
        id = value
        return this
    }

    override fun value2(value: Int?): WorkoutsRecord {
        userId = value
        return this
    }

    override fun value3(value: String?): WorkoutsRecord {
        title = value
        return this
    }

    override fun value4(value: String?): WorkoutsRecord {
        description = value
        return this
    }

    override fun value5(value: OffsetDateTime?): WorkoutsRecord {
        date = value
        return this
    }

    override fun value6(value: String?): WorkoutsRecord {
        timezone = value
        return this
    }

    override fun values(value1: Int?, value2: Int?, value3: String?, value4: String?, value5: OffsetDateTime?, value6: String?): WorkoutsRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        return this
    }

    /**
     * Create a detached, initialised WorkoutsRecord
     */
    constructor(id: Int? = null, userId: Int? = null, title: String? = null, description: String? = null, date: OffsetDateTime? = null, timezone: String? = null): this() {
        this.id = id
        this.userId = userId
        this.title = title
        this.description = description
        this.date = date
        this.timezone = timezone
    }
}
