/*
 * This file is generated by jOOQ.
 */
package dev.anthonybruno.gymbuddy.db.jooq.tables.references


import dev.anthonybruno.gymbuddy.db.jooq.tables.Exercises
import dev.anthonybruno.gymbuddy.db.jooq.tables.FlywaySchemaHistory
import dev.anthonybruno.gymbuddy.db.jooq.tables.Users
import dev.anthonybruno.gymbuddy.db.jooq.tables.WorkoutExercises
import dev.anthonybruno.gymbuddy.db.jooq.tables.Workouts



/**
 * The table <code>public.exercises</code>.
 */
val EXERCISES = Exercises.EXERCISES

/**
 * The table <code>public.flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

/**
 * The table <code>public.users</code>.
 */
val USERS = Users.USERS

/**
 * The table <code>public.workout_exercises</code>.
 */
val WORKOUT_EXERCISES = WorkoutExercises.WORKOUT_EXERCISES

/**
 * The table <code>public.workouts</code>.
 */
val WORKOUTS = Workouts.WORKOUTS
