/*
 * This file is generated by jOOQ.
 */
package dev.anthonybruno.gymbuddy.db.jooq.tables.references


import dev.anthonybruno.gymbuddy.db.jooq.tables.*


/**
 * The table <code>public.exercises</code>.
 */
val EXERCISES = Exercises.EXERCISES

/**
 * The table <code>public.flyway_schema_history</code>.
 */
val FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY

/**
 * The table <code>public.users</code>.
 */
val USERS = Users.USERS

/**
 * The table <code>public.weight_measurements</code>.
 */
val WEIGHT_MEASUREMENTS = WeightMeasurements.WEIGHT_MEASUREMENTS

/**
 * The table <code>public.workout_exercises</code>.
 */
val WORKOUT_EXERCISES = WorkoutExercises.WORKOUT_EXERCISES

/**
 * The table <code>public.workouts</code>.
 */
val WORKOUTS = Workouts.WORKOUTS
