/*
 * This file is generated by jOOQ.
 */
package dev.anthonybruno.gymbuddy.db.jooq.sequences


import dev.anthonybruno.gymbuddy.db.jooq.Public

import org.jooq.Sequence
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType



/**
 * The sequence <code>public.exercises_id_seq</code>
 */
val EXERCISES_ID_SEQ: Sequence<Int> = Internal.createSequence("exercises_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null)

/**
 * The sequence <code>public.users_id_seq</code>
 */
val USERS_ID_SEQ: Sequence<Int> = Internal.createSequence("users_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null)

/**
 * The sequence <code>public.weight_measurements_id_seq</code>
 */
val WEIGHT_MEASUREMENTS_ID_SEQ: Sequence<Int> = Internal.createSequence("weight_measurements_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null)

/**
 * The sequence <code>public.workout_exercises_id_seq</code>
 */
val WORKOUT_EXERCISES_ID_SEQ: Sequence<Int> = Internal.createSequence("workout_exercises_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null)

/**
 * The sequence <code>public.workouts_id_seq</code>
 */
val WORKOUTS_ID_SEQ: Sequence<Int> = Internal.createSequence("workouts_id_seq", Public.PUBLIC, SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null)
